/* Generated by re2c 2.0.3 */

#include "json_type.hpp"

struct scanner{
    char *start = nullptr;
    char *limit = nullptr;
    char *marker = nullptr;
    char *ctxmarker = nullptr;
    int   state = 0;
    json  result;
    int   line = 1;
    int   column = 0;
    std::string msg{};
    int   subline = 1;
    int   subcolumn = 0;

    scanner(const std::string &buffer) {
        this->start = (char *)buffer.data();
        this->limit = this->start + buffer.size();
        this->marker = nullptr;
        this->ctxmarker = nullptr;
        this->line = 1;
        this->column = 0;
        this->state = 0; /* for JSON mode */
    }
};

enum YYCONDTYPE {
	yycJSON,
	yycKEY,
	yycKEY1,
	yycCOMMENTS,
	yycCOMMENT_STR1,
};
